import React from "react";
import type { Metadata } from "next";
import Topbar from "../components/nav-bar/TopBar";
import Bottombar from "../components/nav-bar/BottomBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HomeLayout = ({ children }: any) => {
  return (
    <div className="flex flex-col">
      <div className="">
        <Topbar />
        <Bottombar />
      </div>
      <div>{children}</div>
    </div>
  );
};

export default HomeLayout;
